schema: app/src/main/graphql/schema.graphqls
extensions:
  endpoints:
    first_time:
      url: https://countries.trevorblades.com/
      headers:
        user-agent: JS GraphQL
      introspect: false
